CREATE TABLE `t_agent_order_1_0930` (
                                        `order_id` varchar(32) NOT NULL COMMENT '旺铺管家订单号',
                                        `gateway_merchant_order_id` varchar(48) DEFAULT '' COMMENT '通道方商户订单号',
                                        `merchant_order_id` varchar(48) DEFAULT '' COMMENT '接口传入订单号',
                                        `merchant_id` varchar(32) NOT NULL COMMENT '商户id',
                                        `device_no` varchar(32) DEFAULT '' COMMENT '设备(SN)号',
                                        `agent_no` int(11) NOT NULL COMMENT '代理NO',
                                        `agent_no_tree` varchar(512) NOT NULL COMMENT '代理层级',
                                        `agent_level` int(2) DEFAULT NULL COMMENT '代理层级',
                                        `payway_id` varchar(16) NOT NULL COMMENT '支付方式',
                                        `customer_id` varchar(128) DEFAULT '' COMMENT 'openId',
                                        `order_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单金额',
                                        `order_actual_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '实际到账金额',
                                        `order_status` tinyint(1) DEFAULT '0' COMMENT '支付状态: 0-初始化,1-已支付,2-未支付,3-支付失败,4-支付超时,5-已退款,6-部分退款',
                                        `order_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '实际手续费金额（支付金额*费率）',
                                        `order_rate` decimal(16,5) DEFAULT '0.00000' COMMENT '基础费率',
                                        `order_min` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费下限',
                                        `order_max` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费上限',
                                        `project_no` varchar(32) DEFAULT '' COMMENT '项目Id',
                                        `activity_id` int(3) DEFAULT '0' COMMENT '活动Id',
                                        `unionpay_offers` tinyint(1) DEFAULT '0' COMMENT '是否是银联小额，0-否/1-是',
                                        `annul_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '减免手续费金额',
                                        `settle_type` varchar(4) DEFAULT NULL COMMENT '结算方式',
                                        `is_freeze` tinyint(1) DEFAULT NULL COMMENT '是否冻结交易，0-否，1-是',
                                        `order_time` varchar(24) DEFAULT NULL COMMENT '请求时间(请求时间yyyyMMddhhmmssSSS形式)',
                                        `pay_time` varchar(24) DEFAULT NULL COMMENT '支付成功时间(yyyyMMddhhmmssSSS)',
                                        `order_date` varchar(8) DEFAULT NULL COMMENT '订单日期(yyyyMMdd)',
                                        `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                        `cm_id` int(6) DEFAULT '0' COMMENT '渠道经理编号',
                                        `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                        `bm_id` int(6) DEFAULT '0' COMMENT '业务员编号',
                                        `pay_channel` varchar(6) DEFAULT 'YS' COMMENT '支付渠道',
                                        `reply_code` varchar(16) DEFAULT '' COMMENT '交易应答码',
                                        `reply_msg` varchar(128) DEFAULT '' COMMENT '交易反馈结果',
                                        `create_time` datetime NOT NULL COMMENT '创建时间(yyyy-MM-dd HH:mm:ss)',
                                        `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                        PRIMARY KEY (`order_id`),
                                        KEY `idx_ano_bm` (`agent_no`,`bm_id`) USING BTREE,
                                        KEY `idx_merId_agn` (`merchant_id`,`agent_no`) USING BTREE,
                                        KEY `idx_device_no` (`device_no`) USING BTREE,
                                        KEY `idx_ano_pid` (`agent_no`,`payway_id`) USING BTREE,
                                        KEY `idx_cid` (`cm_id`) USING BTREE,
                                        KEY `idx_anot` (`agent_no_tree`) USING BTREE,
                                        KEY `idx_pch` (`pay_channel`) USING BTREE,
                                        KEY `idx_pno` (`project_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='湖北邮政订单日表';