CREATE TABLE `t_agent_order_1_0930` (
                                        `order_id` varchar(32) NOT NULL COMMENT '旺铺管家订单号',
                                        `gateway_merchant_order_id` varchar(48) DEFAULT '' COMMENT '通道方商户订单号',
                                        `merchant_order_id` varchar(48) DEFAULT '' COMMENT '接口传入订单号',
                                        `merchant_id` varchar(32) NOT NULL COMMENT '商户id',
                                        `device_no` varchar(32) DEFAULT '' COMMENT '设备(SN)号',
                                        `agent_no` int(11) NOT NULL COMMENT '代理NO',
                                        `agent_no_tree` varchar(512) NOT NULL COMMENT '代理层级',
                                        `agent_level` int(2) DEFAULT NULL COMMENT '代理层级',
                                        `payway_id` varchar(16) NOT NULL COMMENT '支付方式',
                                        `customer_id` varchar(128) DEFAULT '' COMMENT 'openId',
                                        `order_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单金额',
                                        `order_actual_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '实际到账金额',
                                        `order_status` tinyint(1) DEFAULT '0' COMMENT '支付状态: 0-初始化,1-已支付,2-未支付,3-支付失败,4-支付超时,5-已退款,6-部分退款',
                                        `order_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '实际手续费金额（支付金额*费率）',
                                        `order_rate` decimal(16,5) DEFAULT '0.00000' COMMENT '基础费率',
                                        `order_min` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费下限',
                                        `order_max` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费上限',
                                        `project_no` varchar(32) DEFAULT '' COMMENT '项目Id',
                                        `activity_id` int(3) DEFAULT '0' COMMENT '活动Id',
                                        `unionpay_offers` tinyint(1) DEFAULT '0' COMMENT '是否是银联小额，0-否/1-是',
                                        `annul_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '减免手续费金额',
                                        `settle_type` varchar(4) DEFAULT NULL COMMENT '结算方式',
                                        `is_freeze` tinyint(1) DEFAULT NULL COMMENT '是否冻结交易，0-否，1-是',
                                        `order_time` varchar(24) DEFAULT NULL COMMENT '请求时间(请求时间yyyyMMddhhmmssSSS形式)',
                                        `pay_time` varchar(24) DEFAULT NULL COMMENT '支付成功时间(yyyyMMddhhmmssSSS)',
                                        `order_date` varchar(8) DEFAULT NULL COMMENT '订单日期(yyyyMMdd)',
                                        `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                        `cm_id` int(6) DEFAULT '0' COMMENT '渠道经理编号',
                                        `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                        `bm_id` int(6) DEFAULT '0' COMMENT '业务员编号',
                                        `pay_channel` varchar(6) DEFAULT 'YS' COMMENT '支付渠道',
                                        `reply_code` varchar(16) DEFAULT '' COMMENT '交易应答码',
                                        `reply_msg` varchar(128) DEFAULT '' COMMENT '交易反馈结果',
                                        `create_time` datetime NOT NULL COMMENT '创建时间(yyyy-MM-dd HH:mm:ss)',
                                        `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                        PRIMARY KEY (`order_id`),
                                        KEY `idx_ano_bm` (`agent_no`,`bm_id`) USING BTREE,
                                        KEY `idx_merId_agn` (`merchant_id`,`agent_no`) USING BTREE,
                                        KEY `idx_device_no` (`device_no`) USING BTREE,
                                        KEY `idx_ano_pid` (`agent_no`,`payway_id`) USING BTREE,
                                        KEY `idx_cid` (`cm_id`) USING BTREE,
                                        KEY `idx_anot` (`agent_no_tree`) USING BTREE,
                                        KEY `idx_pch` (`pay_channel`) USING BTREE,
                                        KEY `idx_pno` (`project_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='湖北邮政订单日表';


CREATE TABLE `t_agent_mer_device_payway_stat_202209` (
                                                         `id` varchar(32) NOT NULL COMMENT '主键',
                                                         `agent_no` int(8) NOT NULL COMMENT '代理No',
                                                         `agent_no_tree` varchar(255) NOT NULL COMMENT '代理层级树',
                                                         `merchant_id` varchar(32) NOT NULL COMMENT '831商户号',
                                                         `trade_date` varchar(8) NOT NULL COMMENT '统计日期 yyyyMMdd',
                                                         `project_no` varchar(32) DEFAULT '' COMMENT '项目编号',
                                                         `device_no` varchar(32) NOT NULL COMMENT '设备编号',
                                                         `device_type` int(2) NOT NULL COMMENT '设备类型0-传统pos,1-扫码枪,2-扫码盒,3-台牌,4-智能pos,5-云音箱,6-刷卡扫码盒,7-刷脸',
                                                         `payway_id` varchar(16) NOT NULL COMMENT '支付方式',
                                                         `order_counts` bigint(32) NOT NULL COMMENT '交易笔数',
                                                         `order_amount` decimal(16,4) NOT NULL COMMENT '交易金额',
                                                         `settle_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '结算金额',
                                                         `fail_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '失败金额',
                                                         `fail_count` bigint(32) DEFAULT '0' COMMENT '失败笔数',
                                                         `refund_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '退款金额',
                                                         `refund_count` bigint(32) DEFAULT '0' COMMENT '退款笔数',
                                                         `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                                         `cm_id` int(11) DEFAULT '0' COMMENT '渠道经理编号',
                                                         `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                                         `bm_id` int(11) DEFAULT '0' COMMENT '业务员编号',
                                                         `create_time` datetime NOT NULL COMMENT '创建时间',
                                                         `update_time` datetime NOT NULL COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                                         `creator` varchar(16) DEFAULT 'admin' COMMENT '创建人',
                                                         `updater` varchar(16) DEFAULT 'admin' COMMENT '更新人',
                                                         `is_deleted` tinyint(1) DEFAULT '1' COMMENT '是否有效 0-失效 1-有效',
                                                         PRIMARY KEY (`id`),
                                                         KEY `idx_ano_date` (`agent_no`,`trade_date`,`device_no`,`payway_id`),
                                                         KEY `idx_anot_date` (`agent_no_tree`,`trade_date`),
                                                         KEY `idx_ano_bm` (`agent_no`,`project_no`,`bm_id`),
                                                         KEY `idx_ano_payway` (`merchant_id`,`trade_date`,`device_no`,`payway_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户支付方式交易数据汇总月表';



CREATE TABLE `t_agent_mer_stat_202208` (
                                           `id` varchar(32) NOT NULL COMMENT '主键',
                                           `agent_no` int(11) NOT NULL COMMENT '代理No',
                                           `agent_no_tree` varchar(255) NOT NULL COMMENT '代理层级树',
                                           `merchant_id` varchar(32) NOT NULL COMMENT '商户编号',
                                           `project_no` varchar(32) DEFAULT '' COMMENT '项目Id',
                                           `trade_date` varchar(8) NOT NULL COMMENT '统计日期(yyyyMMdd)',
                                           `valid_order_amount` decimal(16,4) NOT NULL COMMENT '有效交易金额',
                                           `valid_order_count` bigint(32) NOT NULL COMMENT '有效交易笔数',
                                           `order_amount` decimal(16,4) NOT NULL COMMENT '交易笔数',
                                           `order_count` bigint(32) NOT NULL COMMENT '交易金额',
                                           `order_fee` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '交易手续费',
                                           `order_annul_fee` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '减免交易手续费',
                                           `big_order_amount` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '大于1000的金额总和',
                                           `big_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '大于1000的金额总和',
                                           `device_count` int(11) NOT NULL DEFAULT '0' COMMENT '设备数',
                                           `report_time` datetime NOT NULL COMMENT '入网时间',
                                           `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                           `cm_id` int(11) DEFAULT '0' COMMENT '渠道经理编号',
                                           `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                           `bm_id` int(11) DEFAULT '0' COMMENT '业务员编号',
                                           `create_time` datetime NOT NULL COMMENT '创建时间',
                                           `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                           PRIMARY KEY (`id`),
                                           KEY `idx_ano_bm_date` (`agent_no`,`trade_date`,`bm_id`) USING BTREE,
                                           KEY `idx_ano_date` (`agent_no_tree`,`trade_date`) USING BTREE,
                                           KEY `idx_ano_mer` (`agent_no`,`merchant_id`) USING BTREE,
                                           KEY `idx_mer_date` (`merchant_id`,`trade_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='按商户汇总交易数据汇总月表';

