CREATE TABLE `t_agent_order_1_0930` (
                                        `order_id` varchar(32) NOT NULL COMMENT '旺铺管家订单号',
                                        `gateway_merchant_order_id` varchar(48) DEFAULT '' COMMENT '通道方商户订单号',
                                        `merchant_order_id` varchar(48) DEFAULT '' COMMENT '接口传入订单号',
                                        `merchant_id` varchar(32) NOT NULL COMMENT '商户id',
                                        `device_no` varchar(32) DEFAULT '' COMMENT '设备(SN)号',
                                        `agent_no` int(11) NOT NULL COMMENT '代理NO',
                                        `agent_no_tree` varchar(512) NOT NULL COMMENT '代理层级',
                                        `agent_level` int(2) DEFAULT NULL COMMENT '代理层级',
                                        `payway_id` varchar(16) NOT NULL COMMENT '支付方式',
                                        `customer_id` varchar(128) DEFAULT '' COMMENT 'openId',
                                        `order_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '订单金额',
                                        `order_actual_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '实际到账金额',
                                        `order_status` tinyint(1) DEFAULT '0' COMMENT '支付状态: 0-初始化,1-已支付,2-未支付,3-支付失败,4-支付超时,5-已退款,6-部分退款',
                                        `order_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '实际手续费金额（支付金额*费率）',
                                        `order_rate` decimal(16,5) DEFAULT '0.00000' COMMENT '基础费率',
                                        `order_min` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费下限',
                                        `order_max` decimal(16,4) DEFAULT '0.0000' COMMENT '手续费上限',
                                        `project_no` varchar(32) DEFAULT '' COMMENT '项目Id',
                                        `activity_id` int(3) DEFAULT '0' COMMENT '活动Id',
                                        `unionpay_offers` tinyint(1) DEFAULT '0' COMMENT '是否是银联小额，0-否/1-是',
                                        `annul_fee` decimal(16,4) DEFAULT '0.0000' COMMENT '减免手续费金额',
                                        `settle_type` varchar(4) DEFAULT NULL COMMENT '结算方式',
                                        `is_freeze` tinyint(1) DEFAULT NULL COMMENT '是否冻结交易，0-否，1-是',
                                        `order_time` varchar(24) DEFAULT NULL COMMENT '请求时间(请求时间yyyyMMddhhmmssSSS形式)',
                                        `pay_time` varchar(24) DEFAULT NULL COMMENT '支付成功时间(yyyyMMddhhmmssSSS)',
                                        `order_date` varchar(8) DEFAULT NULL COMMENT '订单日期(yyyyMMdd)',
                                        `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                        `cm_id` int(6) DEFAULT '0' COMMENT '渠道经理编号',
                                        `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                        `bm_id` int(6) DEFAULT '0' COMMENT '业务员编号',
                                        `pay_channel` varchar(6) DEFAULT 'YS' COMMENT '支付渠道',
                                        `reply_code` varchar(16) DEFAULT '' COMMENT '交易应答码',
                                        `reply_msg` varchar(128) DEFAULT '' COMMENT '交易反馈结果',
                                        `create_time` datetime NOT NULL COMMENT '创建时间(yyyy-MM-dd HH:mm:ss)',
                                        `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                        PRIMARY KEY (`order_id`),
                                        KEY `idx_ano_bm` (`agent_no`,`bm_id`) USING BTREE,
                                        KEY `idx_merId_agn` (`merchant_id`,`agent_no`) USING BTREE,
                                        KEY `idx_device_no` (`device_no`) USING BTREE,
                                        KEY `idx_ano_pid` (`agent_no`,`payway_id`) USING BTREE,
                                        KEY `idx_cid` (`cm_id`) USING BTREE,
                                        KEY `idx_anot` (`agent_no_tree`) USING BTREE,
                                        KEY `idx_pch` (`pay_channel`) USING BTREE,
                                        KEY `idx_pno` (`project_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='湖北邮政订单日表';


CREATE TABLE `t_agent_mer_device_payway_stat_202209` (
                                                         `id` varchar(32) NOT NULL COMMENT '主键',
                                                         `agent_no` int(8) NOT NULL COMMENT '代理No',
                                                         `agent_no_tree` varchar(255) NOT NULL COMMENT '代理层级树',
                                                         `merchant_id` varchar(32) NOT NULL COMMENT '831商户号',
                                                         `trade_date` varchar(8) NOT NULL COMMENT '统计日期 yyyyMMdd',
                                                         `project_no` varchar(32) DEFAULT '' COMMENT '项目编号',
                                                         `device_no` varchar(32) NOT NULL COMMENT '设备编号',
                                                         `device_type` int(2) NOT NULL COMMENT '设备类型0-传统pos,1-扫码枪,2-扫码盒,3-台牌,4-智能pos,5-云音箱,6-刷卡扫码盒,7-刷脸',
                                                         `payway_id` varchar(16) NOT NULL COMMENT '支付方式',
                                                         `order_counts` bigint(32) NOT NULL COMMENT '交易笔数',
                                                         `order_amount` decimal(16,4) NOT NULL COMMENT '交易金额',
                                                         `settle_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '结算金额',
                                                         `fail_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '失败金额',
                                                         `fail_count` bigint(32) DEFAULT '0' COMMENT '失败笔数',
                                                         `refund_amount` decimal(16,4) DEFAULT '0.0000' COMMENT '退款金额',
                                                         `refund_count` bigint(32) DEFAULT '0' COMMENT '退款笔数',
                                                         `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                                         `cm_id` int(11) DEFAULT '0' COMMENT '渠道经理编号',
                                                         `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                                         `bm_id` int(11) DEFAULT '0' COMMENT '业务员编号',
                                                         `create_time` datetime NOT NULL COMMENT '创建时间',
                                                         `update_time` datetime NOT NULL COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                                         `creator` varchar(16) DEFAULT 'admin' COMMENT '创建人',
                                                         `updater` varchar(16) DEFAULT 'admin' COMMENT '更新人',
                                                         `is_deleted` tinyint(1) DEFAULT '1' COMMENT '是否有效 0-失效 1-有效',
                                                         PRIMARY KEY (`id`),
                                                         KEY `idx_ano_date` (`agent_no`,`trade_date`,`device_no`,`payway_id`),
                                                         KEY `idx_anot_date` (`agent_no_tree`,`trade_date`),
                                                         KEY `idx_ano_bm` (`agent_no`,`project_no`,`bm_id`),
                                                         KEY `idx_ano_payway` (`merchant_id`,`trade_date`,`device_no`,`payway_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户支付方式交易数据汇总月表';



CREATE TABLE `t_agent_mer_stat_202208` (
                                           `id` varchar(32) NOT NULL COMMENT '主键',
                                           `agent_no` int(11) NOT NULL COMMENT '代理No',
                                           `agent_no_tree` varchar(255) NOT NULL COMMENT '代理层级树',
                                           `merchant_id` varchar(32) NOT NULL COMMENT '商户编号',
                                           `project_no` varchar(32) DEFAULT '' COMMENT '项目Id',
                                           `trade_date` varchar(8) NOT NULL COMMENT '统计日期(yyyyMMdd)',
                                           `valid_order_amount` decimal(16,4) NOT NULL COMMENT '有效交易金额',
                                           `valid_order_count` bigint(32) NOT NULL COMMENT '有效交易笔数',
                                           `order_amount` decimal(16,4) NOT NULL COMMENT '交易笔数',
                                           `order_count` bigint(32) NOT NULL COMMENT '交易金额',
                                           `order_fee` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '交易手续费',
                                           `order_annul_fee` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '减免交易手续费',
                                           `big_order_amount` decimal(16,4) NOT NULL DEFAULT '0.0000' COMMENT '大于1000的金额总和',
                                           `big_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '大于1000的金额总和',
                                           `device_count` int(11) NOT NULL DEFAULT '0' COMMENT '设备数',
                                           `report_time` datetime NOT NULL COMMENT '入网时间',
                                           `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                                           `cm_id` int(11) DEFAULT '0' COMMENT '渠道经理编号',
                                           `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                                           `bm_id` int(11) DEFAULT '0' COMMENT '业务员编号',
                                           `create_time` datetime NOT NULL COMMENT '创建时间',
                                           `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间(yyyy-MM-dd HH:mm:ss)',
                                           PRIMARY KEY (`id`),
                                           KEY `idx_ano_bm_date` (`agent_no`,`trade_date`,`bm_id`) USING BTREE,
                                           KEY `idx_ano_date` (`agent_no_tree`,`trade_date`) USING BTREE,
                                           KEY `idx_ano_mer` (`agent_no`,`merchant_id`) USING BTREE,
                                           KEY `idx_mer_date` (`merchant_id`,`trade_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='按商户汇总交易数据汇总月表';




CREATE TABLE `posx_agent` (
                              `agent_id` varchar(32) NOT NULL COMMENT '代理id',
                              `agent_no` int(11) NOT NULL AUTO_INCREMENT COMMENT '代理号,自增，从1000开始',
                              `agent_tree` varchar(512) DEFAULT NULL COMMENT '代理树,存agent_no值',
                              `parent_id` varchar(32) NOT NULL COMMENT '所属父id，0是admin',
                              `user_type` int(1) NOT NULL COMMENT '用户类型: 1 平台端管理员,2-代理,3-平台端操作员，4-代理操作员',
                              `account` varchar(32) NOT NULL COMMENT '账号名',
                              `name` varchar(64) DEFAULT NULL COMMENT '姓名',
                              `realname` varchar(32) DEFAULT NULL COMMENT '真实姓名',
                              `nickname` varchar(32) DEFAULT NULL COMMENT '昵称',
                              `password` varchar(32) DEFAULT NULL COMMENT '密码',
                              `phone` varchar(64) DEFAULT NULL COMMENT '手机号',
                              `address` varchar(255) DEFAULT NULL COMMENT '地址',
                              `email` varchar(50) DEFAULT NULL COMMENT '邮箱',
                              `islock` int(1) DEFAULT '0' COMMENT '是否锁定 0-否 1-是',
                              `isdel` int(1) DEFAULT '0' COMMENT '是否删除 0-否 1-是',
                              `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
                              `level` int(2) DEFAULT NULL COMMENT '代理等级',
                              `role_id` varchar(32) DEFAULT NULL COMMENT '角色id',
                              `agent_biz_type` int(1) DEFAULT NULL COMMENT '0传统 1直营 2机构 3 邮易付 4江西邮政 5四川邮政 11银行合作 17长春兴业 18四川银行',
                              `rate` decimal(10,6) unsigned zerofill DEFAULT NULL COMMENT '费率',
                              `business_qq` varchar(32) DEFAULT NULL COMMENT '业务联系人QQ',
                              `business_email` varchar(50) DEFAULT NULL COMMENT '联系人邮箱',
                              `business_tel` varchar(20) DEFAULT NULL COMMENT '联系人手机号',
                              `business_name` varchar(64) DEFAULT NULL COMMENT '业务联系人姓名',
                              `bank_company_name` varchar(64) DEFAULT NULL COMMENT '开户名',
                              `bank_no` varchar(128) DEFAULT NULL COMMENT '开户行账号',
                              `bank_addr_province` varchar(64) DEFAULT NULL COMMENT '开户省',
                              `bank_addr_city` varchar(64) DEFAULT NULL COMMENT '开户地',
                              `bank_name` varchar(64) DEFAULT NULL COMMENT '开户行',
                              `bank_sub_name` varchar(64) DEFAULT NULL COMMENT '开户支行名称',
                              `bank_sub_code` varchar(32) DEFAULT NULL COMMENT '支行机构代码',
                              `create_time` datetime NOT NULL COMMENT '创建时间，格式：yyyyMMdd hh:mm:ss',
                              `update_time` datetime NOT NULL COMMENT '修改时间，格式：yyyyMMdd hh:mm:ss',
                              `photo_id` varchar(32) DEFAULT NULL COMMENT '头像ID',
                              `ext1` varchar(128) DEFAULT NULL COMMENT '扩展字段1',
                              `ext2` varchar(256) DEFAULT NULL COMMENT '扩展字段2',
                              `ext3` varchar(512) DEFAULT NULL COMMENT '扩展字段3',
                              `agreement_version` varchar(16) DEFAULT NULL COMMENT '同意的协议版本',
                              `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证',
                              `is_real_name` int(1) unsigned zerofill DEFAULT '0' COMMENT '是否实名认证 0 否 1是',
                              `jpush_id` varchar(50) DEFAULT NULL COMMENT '极光推送id',
                              `audit_flag` int(1) DEFAULT NULL COMMENT '商户入网审核标识，1-开启，0-关闭',
                              `location_flag` int(1) DEFAULT NULL COMMENT '商户交易定位标识，1-开启，0-关闭',
                              `cash_out_fix_settle_price` decimal(10,2) DEFAULT NULL COMMENT '商户提现2000及其以下固定结算底价',
                              `cash_out_settle_price_rate` decimal(10,4) DEFAULT NULL COMMENT '商户提现2000以上结算底价手续费率',
                              `channel_manager` varchar(20) DEFAULT NULL COMMENT '渠道经理名字',
                              `agent_no_tree` varchar(512) DEFAULT NULL COMMENT '代理层级',
                              `password_update_time` datetime DEFAULT NULL COMMENT '密码修改时间',
                              `login_fail_count` int(8) DEFAULT NULL COMMENT '0 登录失败次数',
                              `freeze_time` datetime DEFAULT NULL COMMENT '冻结时间 之前不能登录',
                              `fast_audit_flag` int(8) DEFAULT '0' COMMENT '快速审核标识，0-关闭，1-开启',
                              `activity_flag` int(2) DEFAULT '1' COMMENT '营销活动标识，0-关闭，1-开启',
                              `org_struct_id` int(11) DEFAULT '0' COMMENT '组织结构编号',
                              `org_struct_tree` varchar(50) DEFAULT '0' COMMENT '组织结构树',
                              `cm_id` int(11) DEFAULT '0' COMMENT '渠道经理编号',
                              `ext_field` varchar(100) DEFAULT NULL COMMENT '网点编号',
                              `pay_channel` varchar(20) DEFAULT 'YS' COMMENT '接入通道',
                              `org_level` int(1) DEFAULT '0' COMMENT '机构级别 0-无 1-S级  2-A级 3-B级 4-C级',
                              `mode_number` varchar(32) DEFAULT NULL COMMENT '易生合作模式编号',
                              PRIMARY KEY (`agent_id`),
                              UNIQUE KEY `agent_no` (`agent_no`) USING BTREE,
                              UNIQUE KEY `index_posx_agent_account` (`account`) USING BTREE,
                              KEY `index_posx_agent_parent_id` (`parent_id`) USING BTREE,
                              KEY `index_posx_agent_role_id` (`role_id`) USING BTREE,
                              KEY `index_posx_agent_agent_tree` (`agent_tree`(255)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=105539 DEFAULT CHARSET=utf8 COMMENT='代理表';
